#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication decomposePar
runParallel -s decompose redistributePar -decompose

runParallel renumberMesh -overwrite

runParallel $(getApplication)

runApplication reconstructPar
runParallel -s reconstruct redistributePar -reconstruct

#------------------------------------------------------------------------------
